export const FirestoreCollectionNames = {
  events: 'events',
  integrations: 'integrations',
  responses: 'responses',
  rooms: 'rooms',
  spaces: 'spaces',
  tasks: 'tasks-v2',
  teams: 'teams',
  users: 'users',
  waitlist: 'waitlist',
  webhook: 'webhook',
  bookmarks: 'bookmarks',
  notifications: 'notifications',
  pokes: 'pokes',
  backlog: 'backlog',
  messages: 'messages',
  conversations: 'messages',
};
